kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: route-reader
  namespace: native-aah
  uid: c8a3683f-79bb-4ecf-aaae-d46f64c81b80
  resourceVersion: '309531'
  creationTimestamp: '2024-08-13T10:28:44Z'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2024-08-13T10:28:44Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:rules': {}
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - route.openshift.io
    resources:
      - routes
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: svc-reader
  namespace: native-aah
  uid: be778882-1ab9-4d2c-bf4a-8e41da3bd868
  resourceVersion: '309378'
  creationTimestamp: '2024-08-13T10:28:21Z'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2024-08-13T10:28:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:rules': {}
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - services
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-reader
  namespace: native-aah
  uid: 85302e20-9729-4c3a-8a0c-ac248fb7b17a
  resourceVersion: '310128'
  creationTimestamp: '2024-08-13T10:30:01Z'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2024-08-13T10:30:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:rules': {}
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - endpoints
